name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: Publish NuGet
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      # Publish Alat.Abstractions
      - name: Publish Alat.Abstractions
        uses: rohith/publish-nuget@v2.2.0
        with:
          PROJECT_FILE_PATH: src/Alat.Abstractions/Alat.Abstractions.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          
      # Publish Alat.CommandBus
      - name: Publish Alat.CommandBus
        uses: rohith/publish-nuget@v2.2.0
        with:
          PROJECT_FILE_PATH: src/Alat.CommandBus/Alat.CommandBus.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      
      # Publish Alat.CommandBus.Abstractions
      - name: Publish Alat.CommandBus.Abstractions
        uses: rohith/publish-nuget@v2.2.0
        with:
          PROJECT_FILE_PATH: src/Alat.CommandBus.Abstractions/Alat.CommandBus.Abstractions.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          
      # Publish Alat.Infrastructure
      - name: Publish Alat.Infrastructure
        uses: rohith/publish-nuget@v2.2.0
        with:
          PROJECT_FILE_PATH: src/Alat.Infrastructure/Alat.Infrastructure.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          
      # Publish Alat.Utils
      - name: Publish Alat.Utils
        uses: rohith/publish-nuget@v2.2.0
        with:
          PROJECT_FILE_PATH: src/Alat.Utils/Alat.Utils.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          